### ISSUE TITLE
implement basic responses to highlights

### ISSUE THREAD

**Issue by SparkyRailgun** [wrycu/toss#3] opened 2015-12-26 18:09 UTC
Bot should respond to messages directed at it in turn, but not be able to actually conversate (because it's a dumb bot)

>Sparky: Toss: how are you?
>Toss: I'm fine thanks, Sparky!

>Sparky: trains are the best, isn't that right Toss?
>Sparky: Yep!

It should choose from an array of responses, ideally exposed to the config.

**Comment by wrycu** [comment] 2016-01-18 05:13
Closing as a duplicate of #16.

**Closed by wrycu** 2016-01-18 05:13 UTC
Labels: feature, plugin
